import { expect, test } from '@playwright/test'

test('desktop account journey survives reload and resets', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Account priorities' })).toBeVisible()
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Prepare action' }).click()
  await expect(page.getByRole('button', { name: 'Simulate contact' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Approve script' }).click()
  await page.getByRole('button', { name: 'Simulate contact' }).click()
  await page.getByRole('button', { name: 'Delivery issue unresolved' }).click()
  await page.getByRole('button', { name: 'Record outcome' }).click()
  await page.getByRole('button', { name: /Follow-ups/ }).click()
  await expect(page.getByText('Escalate delivery issue', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reschedule Escalate delivery issue' }).click()
  await page.getByLabel('New due date').fill('2018-09-07')
  await page.getByRole('button', { name: 'Save date' }).click()
  await expect(page.getByText(/Due 7 Sep(t)? 2018/)).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /Follow-ups/ }).click()
  await expect(page.getByText('Escalate delivery issue', { exact: true })).toBeVisible()
  await expect(page.getByText(/Due 7 Sep(t)? 2018/)).toBeVisible()
  await page.getByRole('button', { name: 'Reset demo' }).click()
  await expect(page.getByText('No follow-ups yet')).toBeVisible()
})

test('mobile queue and account detail remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Account priorities' })).toBeVisible()
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'View A09060' }).click()
  await expect(page.getByRole('heading', { name: 'A09060' })).toBeVisible()
  await page.getByRole('button', { name: 'Prepare action' }).click()
  await expect(page.getByRole('button', { name: 'Approve script' })).toBeVisible()
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  await page.setViewportSize({ width: 320, height: 720 })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 320)
})
